LOCAL_PATH := $(call my-dir)


#
# Statically Linked
#

include $(CLEAR_VARS)
LOCAL_MODULE            := sqlite3-a
LOCAL_MODULE_FILENAME   := libsqlite3
LOCAL_SRC_FILES         := ../build/sqlite3.c
LOCAL_C_INCLUDES        := ../build
LOCAL_EXPORT_C_INCLUDES := ../build
LOCAL_CFLAGS            := -DSQLITE_DQS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_MEMSTATUS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
LOCAL_CFLAGS            += -DSQLITE_LIKE_DOESNT_MATCH_BLOBS
LOCAL_CFLAGS            += -DSQLITE_MAX_EXPR_DEPTH=0
LOCAL_CFLAGS            += -DSQLITE_OMIT_DECLTYPE
LOCAL_CFLAGS            += -DSQLITE_OMIT_DEPRECATED
LOCAL_CFLAGS            += -DSQLITE_OMIT_PROGRESS_CALLBACK
LOCAL_CFLAGS            += -DSQLITE_OMIT_SHARED_CACHE
LOCAL_CFLAGS            += -DSQLITE_USE_ALLOCA
LOCAL_CFLAGS            += -DSQLITE_OMIT_AUTOINIT
LOCAL_CFLAGS            += -DSQLITE_THREADSAFE=2
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS3
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS4
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS5
LOCAL_CFLAGS            += -DSQLITE_ENABLE_RTREE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_JSON1
LOCAL_CFLAGS            += -DSQLITE_OMIT_LOAD_EXTENSION
LOCAL_CFLAGS            += -DSQLITE_USE_URI=1
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SESSION
LOCAL_CFLAGS            += -DSQLITE_ENABLE_PREUPDATE_HOOK
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOMATIC_INDEX=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOVACUUM=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_CACHE_SIZE=-4096
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBPAGE_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBSTAT_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DESERIALIZE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_EXPLAIN_COMMENTS
LOCAL_CFLAGS            += -DSQLITE_ENABLE_MEMORY_MANAGEMENT
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SORTER_REFERENCES
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE            := sqlite3-static-cli
LOCAL_MODULE_FILENAME   := sqlite3-static
LOCAL_STATIC_LIBRARIES  := libsqlite3-a
LOCAL_SRC_FILES         := ../build/shell.c ../build/sqlite3.c
LOCAL_C_INCLUDES        := ../build
LOCAL_EXPORT_C_INCLUDES := ../build
LOCAL_CFLAGS            := -DSQLITE_DQS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_MEMSTATUS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
LOCAL_CFLAGS            += -DSQLITE_LIKE_DOESNT_MATCH_BLOBS
LOCAL_CFLAGS            += -DSQLITE_MAX_EXPR_DEPTH=0
LOCAL_CFLAGS            += -DSQLITE_OMIT_DECLTYPE
LOCAL_CFLAGS            += -DSQLITE_OMIT_DEPRECATED
LOCAL_CFLAGS            += -DSQLITE_OMIT_PROGRESS_CALLBACK
LOCAL_CFLAGS            += -DSQLITE_OMIT_SHARED_CACHE
LOCAL_CFLAGS            += -DSQLITE_USE_ALLOCA
LOCAL_CFLAGS            += -DSQLITE_OMIT_AUTOINIT
LOCAL_CFLAGS            += -DSQLITE_THREADSAFE=2
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS3
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS4
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS5
LOCAL_CFLAGS            += -DSQLITE_ENABLE_RTREE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_JSON1
LOCAL_CFLAGS            += -DSQLITE_OMIT_LOAD_EXTENSION
LOCAL_CFLAGS            += -DSQLITE_USE_URI=1
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SESSION
LOCAL_CFLAGS            += -DSQLITE_ENABLE_PREUPDATE_HOOK
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOMATIC_INDEX=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOVACUUM=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_CACHE_SIZE=-4096
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBPAGE_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBSTAT_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DESERIALIZE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_EXPLAIN_COMMENTS
LOCAL_CFLAGS            += -DSQLITE_ENABLE_MEMORY_MANAGEMENT
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SORTER_REFERENCES
LOCAL_CFLAGS            += -fPIE
LOCAL_LDFLAGS           += -fPIE -static
include $(BUILD_EXECUTABLE)


#
# Dynamically Linked
#

include $(CLEAR_VARS)
LOCAL_MODULE            := sqlite3-so
LOCAL_MODULE_FILENAME   := libsqlite3
LOCAL_SRC_FILES         := ../build/sqlite3.c
LOCAL_C_INCLUDES        := ../build
LOCAL_EXPORT_C_INCLUDES := ../build
LOCAL_CFLAGS            := -DSQLITE_DQS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_MEMSTATUS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
LOCAL_CFLAGS            += -DSQLITE_LIKE_DOESNT_MATCH_BLOBS
LOCAL_CFLAGS            += -DSQLITE_MAX_EXPR_DEPTH=0
LOCAL_CFLAGS            += -DSQLITE_OMIT_DECLTYPE
LOCAL_CFLAGS            += -DSQLITE_OMIT_DEPRECATED
LOCAL_CFLAGS            += -DSQLITE_OMIT_PROGRESS_CALLBACK
LOCAL_CFLAGS            += -DSQLITE_OMIT_SHARED_CACHE
LOCAL_CFLAGS            += -DSQLITE_USE_ALLOCA
LOCAL_CFLAGS            += -DSQLITE_OMIT_AUTOINIT
LOCAL_CFLAGS            += -DSQLITE_THREADSAFE=2
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS3
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS4
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS5
LOCAL_CFLAGS            += -DSQLITE_ENABLE_RTREE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_JSON1
LOCAL_CFLAGS            += -DSQLITE_OMIT_LOAD_EXTENSION
LOCAL_CFLAGS            += -DSQLITE_USE_URI=1
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SESSION
LOCAL_CFLAGS            += -DSQLITE_ENABLE_PREUPDATE_HOOK
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOMATIC_INDEX=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOVACUUM=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_CACHE_SIZE=-4096
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBPAGE_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBSTAT_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DESERIALIZE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_EXPLAIN_COMMENTS
LOCAL_CFLAGS            += -DSQLITE_ENABLE_MEMORY_MANAGEMENT
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SORTER_REFERENCES
include $(BUILD_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE            := sqlite3-dynamic-cli
LOCAL_MODULE_FILENAME   := sqlite3-dynamic
LOCAL_SHARED_LIBRARIES  := libsqlite3-so
LOCAL_SRC_FILES         := ../build/shell.c ../build/sqlite3.c
LOCAL_C_INCLUDES        := ../build
LOCAL_EXPORT_C_INCLUDES := ../build
LOCAL_CFLAGS            := -DSQLITE_DQS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_MEMSTATUS=0
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
LOCAL_CFLAGS            += -DSQLITE_LIKE_DOESNT_MATCH_BLOBS
LOCAL_CFLAGS            += -DSQLITE_MAX_EXPR_DEPTH=0
LOCAL_CFLAGS            += -DSQLITE_OMIT_DECLTYPE
LOCAL_CFLAGS            += -DSQLITE_OMIT_DEPRECATED
LOCAL_CFLAGS            += -DSQLITE_OMIT_PROGRESS_CALLBACK
LOCAL_CFLAGS            += -DSQLITE_OMIT_SHARED_CACHE
LOCAL_CFLAGS            += -DSQLITE_USE_ALLOCA
LOCAL_CFLAGS            += -DSQLITE_OMIT_AUTOINIT
LOCAL_CFLAGS            += -DSQLITE_THREADSAFE=2
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS3
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS4
LOCAL_CFLAGS            += -DSQLITE_ENABLE_FTS5
LOCAL_CFLAGS            += -DSQLITE_ENABLE_RTREE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_JSON1
LOCAL_CFLAGS            += -DSQLITE_OMIT_LOAD_EXTENSION
LOCAL_CFLAGS            += -DSQLITE_USE_URI=1
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SESSION
LOCAL_CFLAGS            += -DSQLITE_ENABLE_PREUPDATE_HOOK
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOMATIC_INDEX=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_AUTOVACUUM=1
LOCAL_CFLAGS            += -DSQLITE_DEFAULT_CACHE_SIZE=-4096
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBPAGE_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DBSTAT_VTAB
LOCAL_CFLAGS            += -DSQLITE_ENABLE_DESERIALIZE
LOCAL_CFLAGS            += -DSQLITE_ENABLE_EXPLAIN_COMMENTS
LOCAL_CFLAGS            += -DSQLITE_ENABLE_MEMORY_MANAGEMENT
LOCAL_CFLAGS            += -DSQLITE_ENABLE_SORTER_REFERENCES
LOCAL_CFLAGS            += -fPIE
LOCAL_LDFLAGS           := -fPIE -pie
include $(BUILD_EXECUTABLE)
